formats:
- hdf5
iterations: 1
languages:
- py
max processes: 20
only data: false
par_backend: MPI
parallel: Both
paths:
  path_to_benchmarks: components/benchmarks
  path_to_config: components/handler/
  path_to_plotting: components/visualize/plotting
  path_to_results: components/results
  path_to_tmp: components/tmp
  path_to_visuals: components/visualize
range:
- 10
- 90
ranks:
- 1
runs:
  run02:
    X:
    - - 134217728
    - []
    - f8
stepsize: 5
variable_to_benchmark:
- X
