formats:
- zarr: new
iterations: 10
languages:
- py
par_backend: MPI
parallel: Both
paths:
  path_to_benchmarks: components/benchmarks
  path_to_config: components/handler/
  path_to_plotting: components/visualize/plotting
  path_to_results: components/results
  path_to_tmp: components/tmp
  path_to_visuals: components/visualize
range:
- 10
- 90
ranks: 32
runs:
  run04:
    X:
    - - 1342177280
    - []
  run05:
    X:
    - - 2684354560
    - []
  run06:
    X:
    - - 4026531840
    - []
  run07:
    X:
    - - 5368709120
    - []
  run08:
    X:
    - - 6710886400
    - []
  run09:
    X:
    - - 8053063680
    - []
  run10:
    X:
    - - 9395240960
    - []
  run11:
    X:
    - - 10737418240
    - []
  run12:
    X:
    - - 12079595520
    - []
  run13:
    X:
    - - 13421772800
    - []
stepsize: 5
variable_to_benchmark:
- X
- Y
